#!/bin/bash

ENV="$1"
if [ "$ENV" = "" ]; then
	echo "usage: nodes env"
	exit 1
fi
if [ "$2" = "-do" ]; then
	DOTOKEN="$3"
	DOCKER_MACHINE_DRIVER="digitalocean --digitalocean-access-token $DOTOKEN --digitalocean-image ubuntu-16-04-x64"
else
	DOCKER_MACHINE_DRIVER="virtualbox --virtualbox-memory 1024 --virtualbox-cpu-count 2 --virtualbox-disk-size 10000"
fi

machine ()
{
	docker-machine rm -f $1
	docker-machine create --driver $DOCKER_MACHINE_DRIVER $1
	docker-machine restart $1
	echo "* $1 done"
}

for node in ${ENV}-manager ${ENV}-worker1 ${ENV}-worker2
do
	machine $node &
done
