#!/bin/bash
set -x

DOCKER_MACHINE_DRIVER="virtualbox --virtualbox-memory 1024 --virtualbox-cpu-count 2 --virtualbox-disk-size 10000"
# DOCKER_MACHINE_DRIVER="digitalocean --digitalocean-access-token $DOTOKEN --digitalocean-image ubuntu-16-04-x64"

machine ()
{
	docker-machine rm -f $1
	docker-machine create --driver $DOCKER_MACHINE_DRIVER $1
	docker-machine restart $1
	echo "*** $1 done ***"
}

for node in manager worker1 worker2
do
	machine $node &
done
