#!/bin/bash
set -x

DOCKER_MACHINE_DRIVER="virtualbox  --virtualbox-memory 1024  --virtualbox-cpu-count 2  --virtualbox-disk-size 10000"
# DOCKER_MACHINE_DRIVER="digitalocean  --digitalocean-access-token 0...6  --digitalocean-image ubuntu-16-04-x64"

for node in manager worker1 worker2
do
	docker-machine rm -f $node
	docker-machine create --driver $DOCKER_MACHINE_DRIVER  $node
	docker-machine restart $node
done
