#!/bin/bash

ENV="$1"
if [ "$ENV" = "" ]; then
	echo "usage: rethink env (number of servers per node; default=1)"
	exit 1
fi

NUM=${2-1}

rm ()
{
	echo "* removing ${!#}..."
	eval $* 2>%1
}

for i in $(seq 0 $NUM)
do
	rm docker-machine ssh ${ENV}-manager docker service rm db${i}
done
rm docker-machine ssh ${ENV}-manager docker network rm dbnet

echo "* creating dbnet..."
docker-machine ssh ${ENV}-manager docker network create --driver overlay dbnet

for i in $(seq 0 $NUM)
do
	echo "* creating db${i}data..."
	docker-machine ssh ${ENV}-manager docker volume create --name db${i}data
	echo "* creating db${i}..."
	if [ "$i" = "0" ]; then
		MODE="--replicas 1"
		PUBLISH="--publish 8080:8080"
		CMD=""
	else
		MODE="--mode global"
		PUBLISH=""
		CMD="rethinkdb --join db0:29015 --bind all"
	fi
	docker-machine ssh ${ENV}-manager docker service create --name db${i} ${MODE} ${PUBLISH} --network dbnet --mount src=db${i}data,dst=/data rethinkdb ${CMD}
done

echo "* connecting..."
sleep 30
docker-machine ssh ${ENV}-manager -fNL 8080:localhost:8080
open http://localhost:8080
echo "* done"
