#!/bin/bash

ENV="$1"
if [ "$ENV" = "" ]; then
	echo "usage: rethink env [number of servers per node; default=1]"
	exit 1
fi

NUM=${2-1}

remove ()
{
	echo "* removing ${!#}..."
	eval $* 2>/dev/null
}

for i in $(seq 0 $NUM)
do
	remove docker-machine ssh ${ENV}-manager docker service rm db${i}
done
sleep 5
remove docker-machine ssh ${ENV}-manager docker network rm dbnet
sleep 5
echo "* creating dbnet..."
docker-machine ssh ${ENV}-manager docker network create --driver overlay dbnet

for i in $(seq 0 $NUM)
do
	echo "* creating db${i}data..."
	docker-machine ssh ${ENV}-manager docker volume create --name db${i}data
	echo "* creating db${i}..."
	if [ "$i" = "0" ]; then
		docker-machine ssh ${ENV}-manager docker service create --name db0 --network dbnet --mount src=db0data,dst=/data --publish 8080:8080 rethinkdb
		sleep 30
	else
		docker-machine ssh ${ENV}-manager docker service create --name db${i} --network dbnet --mount src=db${i}data,dst=/data --mode global rethinkdb rethinkdb --join db0 --bind all
	fi
done

echo "* connecting..."
sleep 30
docker-machine ssh ${ENV}-manager -fNL 8080:localhost:8080
open http://localhost:8080
echo "* done"
