#!/bin/bash
set -x

docker-machine ssh manager docker network create --driver overlay dbnet

docker-machine ssh manager docker volume create --name db1data
docker-machine ssh manager docker service rm db1
docker-machine ssh manager docker service create --name db1  --replicas 1  --network dbnet  --mount src=db1data,dst=/data --publish 8080:8080 rethinkdb

docker-machine ssh manager docker volume create --name dbdata
docker-machine ssh manager docker service rm db
docker-machine ssh manager docker service create --name db --mode global --network dbnet  --mount src=dbdata,dst=/data rethinkdb rethinkdb --join db1:29015 --bind all

docker-machine ssh manager -fNL 8080:localhost:8080
sleep 10
open http://localhost:8080
