#!/bin/bash
set -x

docker-machine ssh manager docker service rm db
for i in $(seq 1 ${1-1})
do
	docker-machine ssh manager docker service rm db"$i"
done
docker-machine ssh manager docker network rm dbnet
docker-machine ssh manager docker network create --driver overlay dbnet

docker-machine ssh manager docker volume create --name dbdata
docker-machine ssh manager docker service create --name db --replicas 1 --network dbnet --mount src=dbdata,dst=/data --publish 8080:8080 rethinkdb

for i in $(seq 1 ${1-1})
do
	docker-machine ssh manager docker volume create --name db"$i"data
	docker-machine ssh manager docker service create --name db"$i" --mode global --network dbnet --mount src=db"$i"data,dst=/data rethinkdb rethinkdb --join db:29015 --bind all

done

sleep 10
docker-machine ssh manager -fNL 8080:localhost:8080
open http://localhost:8080
