#!/bin/bash

ENV="$1"
if [ "$ENV" = "" ]; then
	echo "usage: swarm env"
	exit 1
fi

MANAGER_IP="$(docker-machine ip ${ENV}-manager)"
docker-machine ssh ${ENV}-manager docker swarm init --advertise-addr $MANAGER_IP

TOKEN="$(docker-machine ssh ${ENV}-manager docker swarm join-token --quiet worker)"
for i in {1..2}
do
	docker-machine ssh ${ENV}-worker$i docker swarm join --token $TOKEN $MANAGER_IP:2377
done
